name: Publish

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install packages
        run: npm ci

      - name: Build app
        run: npm run build && npm run export && touch ./out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: public
          FOLDER: out
